name: spotify_redesign
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  animations: ^2.1.1
  cached_network_image: ^3.4.1
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.1.0
  google_fonts: ^8.0.1
  just_audio: ^0.10.5
  palette_generator: ^0.3.3+4
  riverpod_annotation: ^4.0.0
  material_new_shapes: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.11.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true
